### PR TITLE
Added OL3 example

### PR DESCRIPTION
**Pull request by bogdanvaduva**

### CODE REVIEW

**Comment by kekscom** [comment]
I did not forget you! There are a few bigger changes in the background which will make this a perfect fit. Give me a few days.
Thanks!

**Comment by markgetafe** [comment]
Hi kekscom! How is it going this request?

**Comment by kekscom** [comment]
I've modified build scripts accordingly.
It's working, but far from good.
Updating perspective during move has to be improved.

**Comment by bogdanvaduva** [comment]
Yes,  I know there are a lot to be done there. It's just an example.
Regards,
Bogdan

**Comment by kekscom** [comment]
If one doesn't mind to improve this, I'd be glad.
However, nice to deal with OL3 too.

**Pull request merged**
