### PR TITLE
OpenLayers 5 Support

### PR DESCRIPTION
**Pull request by jmclayt**
…which works with OpenLayers 5

### CODE REVIEW

**Comment by kekscom** [comment]
Hi,
Thank you very much for contributing!
What would be a setup to test this?

I'd not do this change on dist files as they have tendency to be overwritten on build.
I'm fine to put this in the right place later on.

**Comment by jmclayt** [comment]
@kekscom I've added an example under test and removed OSMBuildings-OL5.debug.js under dist. The example I added has a package.json and uses parcel. I have a README that examples the process.

**Comment by kekscom** [comment]
Apologies for the delay.
This looks really good and the additions making it very usable.
Thanks!

**Comment by jmclayt** [comment]
Awesome, again, thanks for continuing to maintain OSMBuildings.

**Pull request merged**
